// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKInJf66-ycX1cAGek6d4wPBT5axmKmuM',
    appId: '1:1094892955782:ios:a2c576d46ce62c87488907',
    messagingSenderId: '1094892955782',
    projectId: 'flutterfinalproject2024',
    storageBucket: 'flutterfinalproject2024.firebasestorage.app',
    iosBundleId: 'com.example.finaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKInJf66-ycX1cAGek6d4wPBT5axmKmuM',
    appId: '1:1094892955782:ios:a2c576d46ce62c87488907',
    messagingSenderId: '1094892955782',
    projectId: 'flutterfinalproject2024',
    storageBucket: 'flutterfinalproject2024.firebasestorage.app',
    iosBundleId: 'com.example.finaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHUVvBuzZYOq5N-XDDAYUbdScP3DCtUSo',
    appId: '1:1094892955782:web:b8ecbc3343921d5c488907',
    messagingSenderId: '1094892955782',
    projectId: 'flutterfinalproject2024',
    authDomain: 'flutterfinalproject2024.firebaseapp.com',
    storageBucket: 'flutterfinalproject2024.firebasestorage.app',
    measurementId: 'G-7LPSGMDTX4',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHUVvBuzZYOq5N-XDDAYUbdScP3DCtUSo',
    appId: '1:1094892955782:web:b8ecbc3343921d5c488907',
    messagingSenderId: '1094892955782',
    projectId: 'flutterfinalproject2024',
    authDomain: 'flutterfinalproject2024.firebaseapp.com',
    storageBucket: 'flutterfinalproject2024.firebasestorage.app',
    measurementId: 'G-7LPSGMDTX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdJlz7py8hUElcuimiCjk6nszEm6YqZ-o',
    appId: '1:1094892955782:android:51df4327116f7cab488907',
    messagingSenderId: '1094892955782',
    projectId: 'flutterfinalproject2024',
    storageBucket: 'flutterfinalproject2024.firebasestorage.app',
  );

}